use_frameworks!
platform :ios, '13.3'

target 'NextcloudConfig_Example' do
  pod 'NextcloudConfig', :path => '../'
  pod 'SwiftLint'
  target 'NextcloudConfig_Tests' do
    inherit! :search_paths
  end
end
